name: CI
on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE"
jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install LLVM tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy clang-format

      - name: Check code formatting
        run: |
          find . -name "*.c" -o -name "*.h" | xargs clang-format -style=file -n -Werror

      - name: Run clang-tidy
        run: |
          find . -name "*.c" -o -name "*.h" -type f | \
          xargs clang-tidy -p build --checks=bugprone-*,cert-*,clang-analyzer-*,performance-*,portability-*,readability-*

  build-gcc:
    name: "GCC build"
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Configure with CMake
        run: mkdir -p build && cmake -S . -B ./build

      - name: Build with GCC
        working-directory: ./build
        run: cmake --build .

      - name: Run tests
        working-directory: ./build
        run: ctest --output-on-failure

  build-clang:
    name: "Clang build"
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake

      - name: Configure with CMake
        env:
          CC: clang
        run: mkdir -p build && cmake -S . -B ./build

      - name: Build with Clang
        working-directory: ./build
        run: cmake --build .

  build-msvc:
    name: "MSVC build"
    runs-on: windows-latest
    needs: [lint]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Configure with CMake
        run: |
          mkdir -p build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64

      - name: Build with MSVC
        working-directory: ./build
        run: cmake --build . --config Release
